jobs:
  download-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare playlist folder
        run: |
          mkdir -p playlist
          rm -rf playlist/*

      - name: Read link.json and download m3u8 files
        run: |
          cat link.json | jq -c '.[]' | while read i; do
            name=$(echo $i | jq -r '.name')
            url=$(echo $i | jq -r '.url')
            echo "📥 Downloading $name..."
            curl -L "$url" -H "User-Agent: Mozilla/5.0" -H "Referer: https://live.artofknot.com/" -o "playlist/$name.m3u8"
          done

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add playlist/*.m3u8
          git commit -m "🔁 Updated m3u8 from JSON - $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || true
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
